languageCode = "fr"
title = "Riposte Collective"
baseURL = "https://riposte-collective.org/"
canonifyURLs = true
theme = "cupper"
publishDir = "docs"

[params]
  description = "Riposte Collective"
  codePenUser = "Heydon"
