languageCode = "fr"
title = "Riposte Collective"
baseURL = ""
canonifyURLs = true
theme = "cupper"
publishDir = "docs"

[params]
#  description = "![images/logo.svg](images/logo.svg)"
  Twitter = "https://twitter.com/riposte_col"
  Tiktok = "https://www.tiktok.com/@ripostecollective"
  Instagram = "https://www.instagram.com/ripostecollective/"
  Mail = ""
