languageCode = "en-us"
title = "Blueprint"
baseURL = "https://alliberry.github.io/cupper-test/"
canonifyURLs = true
theme = "cupper"
publishDir = "docs"

[params]
  description = "A test to see if Cupper will make all our hopes and dreams come true"
  codePenUser = ""
