languageCode = "en-us"
title = "Cupper"
baseURL = "https://thepaciellogroup.github.io/cupper/"
canonifyURLs = true
theme = "cupper"
publishDir = "docs"

# Search
[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
  description = "Documentation for the **Cupper** documentation builder, built with **Cupper** itself."
  codePenUser = "Heydon"
