languageCode = "en-us"
title = "Unicef hiring"
baseURL = "https://erikkroes.github.io/unicef/"
canonifyURLs = true
theme = "cupper"
publishDir = "docs"

[params]
  description = "Inspection of https://jobs.unicef.org/"
  codePenUser = "Heydon"
