languageCode = "en-us"
title = "Mimir"
baseURL = "https://mazzucchelli.github.io/mimir/"
canonifyURLs = true
theme = "cupper"
publishDir = "docs"

[params]
  description = "Just a place where I store notes!"
